name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: RakSrinaNa
          template: repository
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          plugin_followup: yes
          
          plugin_lines: yes
          
          plugin_languages: yes
          
          plugin_isocalendar: yes
          
          plugin_introduction: yes
          
          plugin_skyline: yes
          plugin_skyline_frames: 30
          plugin_skyline_quality: 0.5
          plugin_skyline_year: current-year
